import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({auth:vi.fn(),update:vi.fn(),get:vi.fn(),audit:vi.fn(),transaction:vi.fn()}));
vi.mock('@/lib/auth',()=>({auth:m.auth}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
vi.mock('@/lib/db',()=>({db:{$transaction:m.transaction}}));
import {restoreTransaction} from '../services/transaction-service';
import {DELETE} from '../app/api/entries/bulk/route';
import {POST} from '../app/api/entries/[id]/restore/route';
const date='2026-10-01T00:00:00.000Z';
const before={id:'a',reference:'IMP-a',status:'VOIDED',updatedAt:new Date(date),allocations:[{amount:10}],transfer:null,exchange:null};
beforeEach(()=>{vi.resetAllMocks();m.transaction.mockImplementation(fn=>fn({transaction:{updateMany:m.update,findUniqueOrThrow:m.get},auditLog:{create:m.audit}}));m.get.mockResolvedValueOnce(before).mockResolvedValue({...before,status:'ACTIVE'});m.update.mockResolvedValue({count:1})});
it('restores status atomically without changing ledger lines and audits original values',async()=>{await restoreTransaction('a',{updatedAt:date});expect(m.transaction).toHaveBeenCalledTimes(1);expect(m.update.mock.calls[0][0]).toMatchObject({where:{id:'a',status:'VOIDED',updatedAt:new Date(date)},data:{status:'ACTIVE'}});expect(Object.keys(m.update.mock.calls[0][0].data).sort()).toEqual(['status','updatedAt']);expect(m.audit.mock.calls[0][0].data).toMatchObject({action:'RESTORE',beforeData:{status:'VOIDED',allocations:[{amount:10}]},afterData:{status:'ACTIVE',reference:'IMP-a'}})});
it('rejects stale versions before writing',async()=>{await expect(restoreTransaction('a',{updatedAt:'2026-10-02T00:00:00.000Z'})).rejects.toThrow('changed');expect(m.update).not.toHaveBeenCalled()});
it('rejects already active entries',async()=>{m.get.mockReset().mockResolvedValue({...before,status:'ACTIVE'});await expect(restoreTransaction('a',{updatedAt:date})).rejects.toThrow('already active');expect(m.update).not.toHaveBeenCalled()});
it('rejects concurrent changes without a restore audit',async()=>{m.update.mockResolvedValue({count:0});await expect(restoreTransaction('a',{updatedAt:date})).rejects.toThrow('changed');expect(m.audit).not.toHaveBeenCalled()});
it('requires authentication and validates restore input',async()=>{const req=()=>new Request('http://localhost',{method:'POST',body:'{}'});const context={params:Promise.resolve({id:'a'})};expect((await POST(req(),context)).status).toBe(401);m.auth.mockResolvedValue({user:{name:'test'}});expect((await POST(req(),context)).status).toBe(400);expect(m.transaction).not.toHaveBeenCalled()});
it('disables the old bulk endpoint without touching data',async()=>{expect((await DELETE()).status).toBe(401);m.auth.mockResolvedValue({user:{name:'test'}});expect((await DELETE()).status).toBe(410);expect(m.transaction).not.toHaveBeenCalled()});
