import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({auth:vi.fn(),prepare:vi.fn(),token:vi.fn(),verify:vi.fn(),commit:vi.fn(),options:vi.fn(),workbook:vi.fn()}));
vi.mock('@/lib/auth',()=>({auth:m.auth}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
vi.mock('@/lib/import-workbook',()=>({IMPORT_BYTES:2*1024*1024,makeImportWorkbook:m.workbook}));
vi.mock('@/services/import-service',()=>({prepareImport:m.prepare,importToken:m.token,verifyImportToken:m.verify,commitImport:m.commit,loadImportOptions:m.options}));
import {POST} from '../app/api/import/route';import {GET} from '../app/api/import/template/route';
function request(mode='preview',name='test.xlsx'){const form=new FormData();form.set('file',new File(['test'],name));form.set('mode',mode);form.set('token','preview-token');return new Request('http://localhost/api/import',{method:'POST',body:form})}
beforeEach(()=>{vi.resetAllMocks();m.prepare.mockResolvedValue({rows:[{row:5,reference:'IMP-a',account:'Cash (OMR)',category:'Salary',data:{type:'INCOME',transactionDate:'2026-01-01',amount:12,description:'Salary',notes:''},summary:[]}],errors:[],existing:new Set()});m.token.mockReturnValue('preview-token')});
it('requires authentication for templates and uploads',async()=>{expect((await GET()).status).toBe(401);expect((await POST(request())).status).toBe(401);expect(m.prepare).not.toHaveBeenCalled();expect(m.options).not.toHaveBeenCalled()});
it('previews without writing, then requires a valid token for commit',async()=>{m.auth.mockResolvedValue({user:{name:'test'}});let response=await POST(request());expect(response.status).toBe(200);expect((await response.json()).count).toBe(1);expect(m.commit).not.toHaveBeenCalled();m.verify.mockImplementationOnce(()=>{throw new Error('Preview again')});expect((await POST(request('commit'))).status).toBe(400);expect(m.commit).not.toHaveBeenCalled();m.commit.mockResolvedValue({imported:1,skipped:0});response=await POST(request('commit'));expect(response.status).toBe(200);expect(m.commit).toHaveBeenCalledTimes(1)});
it('blocks invalid rows and unsupported files before any writes',async()=>{m.auth.mockResolvedValue({user:{name:'test'}});expect((await POST(request('preview','bad.xls'))).status).toBe(400);expect(m.prepare).not.toHaveBeenCalled();m.prepare.mockResolvedValue({rows:[],errors:['Row 5: Choose an account'],existing:new Set()});const response=await POST(request('commit'));expect(response.status).toBe(400);expect(await response.json()).toMatchObject({errors:['Row 5: Choose an account']});expect(m.commit).not.toHaveBeenCalled()});
