import { expect,it,vi } from 'vitest';
import ExcelJS from 'exceljs';
vi.mock('@/lib/db',()=>({db:{}}));
import { makeImportWorkbook,readImportWorkbook,accountLabel,categoryLabel,type ImportOptions } from '../lib/import-workbook';
const options:ImportOptions={accounts:[{id:'cash',accountName:'Cash',type:'CASH',currencyId:'omr',currency:{code:'OMR'}},{id:'bank',accountName:'Bank',type:'BANK',currencyId:'omr',currency:{code:'OMR'}},{id:'india',accountName:'India',type:'BANK',currencyId:'inr',currency:{code:'INR'}}],categories:[{id:'food',name:'Food',type:'EXPENSE',parentId:null},{id:'dining',name:'Dining',type:'EXPENSE',parentId:'food'},{id:'salary',name:'Salary',type:'INCOME',parentId:null}]};
async function fixture(){const book=await makeImportWorkbook(options);const sheet=book.getWorksheet('Transactions')!;const id=sheet.getCell('N5').value;sheet.getRow(5).values=['2026-09-30','EXPENSE',20,accountLabel(options.accounts[0]),categoryLabel(options.categories[0]),'Dining','Lunch','',null,null,null,accountLabel(options.accounts[1]),8,id];return {book,sheet}}
const bytes=async(book:ExcelJS.Workbook)=>Buffer.from(await book.xlsx.writeBuffer());
it('exports dropdown names and dependent category validations through an XLSX round trip',async()=>{const {book}=await fixture();const reopened=new ExcelJS.Workbook();await reopened.xlsx.load(await bytes(book) as unknown as ExcelJS.Buffer);const s=reopened.getWorksheet('Transactions')!;expect(s.getCell('D5').dataValidation.formulae).toEqual(['Accounts']);expect(s.getCell('E204').dataValidation.formulae?.[0]).toContain('B204');expect(s.getCell('F5').dataValidation.formulae?.[0]).toContain('VLOOKUP(E5');expect(reopened.definedNames.getRanges('Accounts').ranges[0]).toContain('$A$2:$A$4');expect(reopened.getWorksheet('Lists')!.getCell('J2').value).toBe('Dining')});
it('parses dates, optional subcategories and split allocations without changing the total',async()=>{const {book}=await fixture();const result=await readImportWorkbook(await bytes(book),options);expect(result.errors).toEqual([]);expect(result.rows).toHaveLength(1);expect(result.rows[0].data).toMatchObject({categoryId:'dining',currencyId:'omr',amount:20,allocations:[{accountId:'cash',amount:12},{accountId:'bank',amount:8}]});expect(result.rows[0].reference).toMatch(/^IMP-/)});
it('parses native Excel dates and supports parent-only income',async()=>{const {book,sheet}=await fixture();sheet.getRow(5).values=[new Date('2026-10-01'),'INCOME',100,accountLabel(options.accounts[1]),categoryLabel(options.categories[2]),'','Salary','',null,null,null,null,null,'stable-id-123'];const r=await readImportWorkbook(await bytes(book),options);expect(r.errors).toEqual([]);expect(r.rows[0].data).toMatchObject({transactionDate:'2026-10-01',categoryId:'salary'})});
it('parses transfers and exchanges with both currencies and destination amounts',async()=>{const {book,sheet}=await fixture();sheet.getRow(5).values=['2026-10-01','TRANSFER',10,accountLabel(options.accounts[0]),'','','Move','',accountLabel(options.accounts[1]),null,null,null,null,'transfer-123'];sheet.getRow(6).values=['2026-10-01','EXCHANGE',10,accountLabel(options.accounts[0]),'','','Exchange','',accountLabel(options.accounts[2]),220,2190,null,null,'exchange-123'];const r=await readImportWorkbook(await bytes(book),options);expect(r.errors).toEqual([]);expect(r.rows[1].data).toMatchObject({sourceAmount:10,exchangeRate:220,actualDestinationAmount:2190,destinationAccountId:'india'})});
it('rejects formulas, wrong currencies, invalid dates and repeated IDs with row numbers',async()=>{const {book,sheet}=await fixture();sheet.getCell('G5').value={formula:'1+1',result:2};let r=await readImportWorkbook(await bytes(book),options);expect(r.errors[0]).toContain('Row 5');expect(r.errors[0]).toContain('not a formula');sheet.getCell('G5').value='Lunch';sheet.getCell('L5').value=accountLabel(options.accounts[2]);r=await readImportWorkbook(await bytes(book),options);expect(r.errors[0]).toContain('same currency');sheet.getCell('L5').value=accountLabel(options.accounts[1]);sheet.getCell('A5').value='2026-02-30';r=await readImportWorkbook(await bytes(book),options);expect(r.errors).toHaveLength(1);sheet.getCell('A5').value='2026-09-30';sheet.getRow(6).values=sheet.getRow(5).values;r=await readImportWorkbook(await bytes(book),options);expect(r.errors[0]).toContain('Duplicate Import ID')});
it('uses a stable import reference for retries and rejects non-XLSX bytes',async()=>{const {book}=await fixture();const buffer=await bytes(book);expect((await readImportWorkbook(buffer,options)).rows[0].reference).toBe((await readImportWorkbook(buffer,options)).rows[0].reference);await expect(readImportWorkbook(Buffer.from('bad'),options)).rejects.toThrow()});
