import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { money } from "@/lib/format";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const { from, to } = await searchParams; const start = from ? new Date(from) : new Date(new Date().getFullYear(), new Date().getMonth(), 1); const end = to ? new Date(to) : new Date();
  const rows = await db.transaction.findMany({ where: { status: "ACTIVE", transactionDate: { gte: start, lte: end }, type: { in: ["INCOME", "EXPENSE"] } }, include: { category: true, allocations: { include: { account: { include: { currency: true } } } } } });
  const codes = [...new Set(rows.map((r) => r.allocations[0]?.account.currency.code).filter(Boolean))] as string[];
  return <><PageHeader title="Summary & Reports" description="Overview → analysis → underlying transactions" actions={<a className="btn-secondary" href={`/api/export?from=${start.toISOString().slice(0,10)}&to=${end.toISOString().slice(0,10)}`}>Export CSV</a>}/><form className="card mb-6 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><div><label>From</label><input type="date" name="from" defaultValue={start.toISOString().slice(0,10)}/></div><div><label>To</label><input type="date" name="to" defaultValue={end.toISOString().slice(0,10)}/></div><div className="flex items-end"><button className="btn-primary">Apply</button></div></form><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{codes.map((code) => { const income = rows.filter((r) => r.type === "INCOME" && r.allocations[0]?.account.currency.code === code).reduce((s,r) => s + Number(r.amount), 0); const expense = rows.filter((r) => r.type === "EXPENSE" && r.allocations[0]?.account.currency.code === code).reduce((s,r) => s + Number(r.amount), 0); return <div className="card" key={code}><p className="text-sm text-slate-500">{code} performance</p><dl className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Income</dt><dd className="font-semibold text-emerald-600">{money(income, code)}</dd></div><div className="flex justify-between"><dt>Expense</dt><dd className="font-semibold text-rose-600">{money(expense, code)}</dd></div><div className="flex justify-between border-t pt-2 dark:border-slate-800"><dt>Net</dt><dd className="font-bold">{money(income-expense, code)}</dd></div></dl></div>; })}</div><section className="card mt-6"><h2 className="mb-4 font-semibold">Expense by category</h2>{codes.map((code) => <div key={code} className="mb-6"><h3 className="mb-2 text-sm font-semibold text-slate-500">{code}</h3>{Object.entries(Object.groupBy(rows.filter((r) => r.type === "EXPENSE" && r.allocations[0]?.account.currency.code === code), (r) => r.category?.name ?? "Uncategorized")).map(([category, items]) => <div className="flex justify-between border-t py-2 text-sm dark:border-slate-800" key={category}><span>{category}</span><strong>{money((items ?? []).reduce((s,r) => s + Number(r.amount), 0), code)}</strong></div>)}</div>)}</section></>;
}
