import { addAccount } from "@/app/actions";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { isoDate, money } from "@/lib/format";
import { getFinancialPosition } from "@/services/balance-service";

export default async function WalletsPage() {
  const [position, currencies] = await Promise.all([getFinancialPosition(), db.currency.findMany({ where: { status: "ACTIVE" }, orderBy: { code: "asc" } })]);
  return <><PageHeader title="Wallets & Banks" description="Every place where your money is held"/><div className="grid gap-5 lg:grid-cols-2">{position.map((currency) => <section className="card" key={currency.id}><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{currency.code} accounts</p><h2 className="text-2xl font-bold">{money(currency.available, currency.code, currency.decimals)}</h2></div><span className="rounded-xl bg-emerald-50 px-3 py-2 font-bold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{currency.code}</span></div><div className="mt-5 divide-y dark:divide-slate-800">{currency.accounts.map((a) => <div key={a.id} className="flex justify-between py-3"><div><p className="font-medium">{a.name}</p><p className="text-xs text-slate-400">{a.type}</p></div><strong>{money(a.available, currency.code, currency.decimals)}</strong></div>)}</div></section>)}</div><section className="card mt-6 max-w-2xl"><h2 className="mb-4 font-semibold">Add bank account</h2><form action={addAccount} className="grid gap-4 sm:grid-cols-2"><div><label>Currency</label><select name="currencyId" required>{currencies.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></div><div><label>Account name</label><input name="accountName" placeholder="Bank Muscat" required/></div><div><label>Bank name</label><input name="bankName" placeholder="Optional legal bank name"/></div><div><label>Opening balance</label><input name="openingAmount" type="number" step="0.0001" defaultValue="0" required/></div><div><label>Opening date</label><input name="openingDate" type="date" defaultValue={isoDate()} required/></div><div className="flex items-end"><button className="btn-primary">Add account</button></div></form></section></>;
}
