import { addAccount } from "@/app/actions";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { isoDate, money } from "@/lib/format";
import { getFinancialPosition } from "@/services/balance-service";
import { Wallet, Landmark, Plus } from "lucide-react";
export default async function WalletsPage() {
  const [position, currencies] = await Promise.all([getFinancialPosition(), db.currency.findMany({ where: { status: "ACTIVE" }, orderBy: { code: "asc" } })]);
  return <><PageHeader title="Wallets & Banks" description="A home for every account and every currency."/><div className="grid gap-5 lg:grid-cols-2">{position.map(currency => <section className="card" key={currency.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">{currency.code} · Available across accounts</p><h2 className="mt-3 !text-3xl tracking-tight">{money(currency.available,currency.code,currency.decimals)}</h2></div><span className="icon-tile text-emerald-700"><Wallet size={21}/></span></div><div className="mt-6 space-y-2">{currency.accounts.map(a => <div key={a.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="icon-tile !bg-white dark:!bg-slate-900">{a.type === "BANK" ? <Landmark size={18}/> : <Wallet size={18}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{a.name}</p><p className="mt-1 text-[11px] capitalize text-muted">{a.type.toLowerCase()} account</p></div><strong className="text-right text-sm">{money(a.available,currency.code,currency.decimals)}</strong></div>)}</div></section>)}</div>
  <section className="card mt-6 max-w-3xl"><div className="mb-6 flex items-center gap-3"><span className="icon-tile text-emerald-700"><Plus size={20}/></span><div><h2>Add a bank account</h2><p className="mt-1 text-xs text-muted">Keep your bank balance alongside your cash wallets.</p></div></div><form action={addAccount} className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="wallet-currency">Currency</label><select id="wallet-currency" name="currencyId" required>{currencies.map(c => <option key={c.id} value={c.id}>{c.code}</option>)}</select></div><div><label htmlFor="wallet-name">Account name</label><input id="wallet-name" name="accountName" placeholder="Bank Muscat" required/></div><div><label htmlFor="bank-name">Bank name</label><input id="bank-name" name="bankName" placeholder="Optional legal bank name"/></div><div><label htmlFor="opening-amount">Opening balance</label><input id="opening-amount" name="openingAmount" type="number" step="0.0001" defaultValue="0" required/></div><div><label htmlFor="opening-date">Opening date</label><input id="opening-date" name="openingDate" type="date" defaultValue={isoDate()} required/></div><div className="flex items-end"><button className="btn-primary w-full sm:w-auto"><Plus size={17}/>Add account</button></div></form></section></>;
}
