import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";

type Issue = { level: "ERROR" | "WARNING"; title: string; detail: string; href?: string };
export default async function DataHealthPage() {
  const [transactions, transfers, exchanges, debts] = await Promise.all([db.transaction.findMany({ where: { status: "ACTIVE" }, include: { allocations: { include: { account: true } } } }), db.transfer.findMany({ include: { sourceAccount: true, destinationAccount: true } }), db.exchange.findMany({ include: { sourceAccount: true, destinationAccount: true } }), db.debtTransaction.findMany({ include: { account: true } })]);
  const issues: Issue[] = [];
  for (const t of transactions.filter((x) => x.type === "INCOME" || x.type === "EXPENSE")) { const allocated = t.allocations.reduce((s,a) => s + Number(a.amount), 0); if (Math.abs(allocated - Number(t.amount)) > 0.0001) issues.push({ level: "ERROR", title: "Allocation mismatch", detail: `${t.reference}: entry ${t.amount}, allocations ${allocated}`, href: `/entries/${t.id}` }); if (t.allocations.some((a) => a.account.currencyId !== t.currencyId)) issues.push({ level: "ERROR", title: "Allocation currency mismatch", detail: t.reference, href: `/entries/${t.id}` }); }
  for (const t of transfers) if (t.sourceAccount.currencyId !== t.destinationAccount.currencyId || t.sourceAccountId === t.destinationAccountId) issues.push({ level: "ERROR", title: "Invalid transfer relationship", detail: t.transactionId });
  for (const e of exchanges) if (e.sourceAccount.currencyId === e.destinationAccount.currencyId) issues.push({ level: "ERROR", title: "Invalid exchange relationship", detail: e.transactionId });
  for (const d of debts) if (d.account.currencyId !== d.currencyId) issues.push({ level: "ERROR", title: "Debt/account currency mismatch", detail: d.reference });
  return <><PageHeader title="Data Health" description="Structural validation rebuilt directly from source records" actions={<Link href="/backup" className="btn-secondary">Backup & Restore</Link>}/><section className="card"><div className={`mb-5 rounded-xl p-4 ${issues.length ? "bg-amber-50 text-amber-800 dark:bg-amber-950 dark:text-amber-200" : "bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200"}`}><p className="font-semibold">{issues.length ? `${issues.length} issue(s) need attention` : "All structural checks passed"}</p><p className="mt-1 text-sm">Checked allocations, currency relationships, transfers, exchanges, and debt accounts.</p></div><div className="space-y-3">{issues.map((issue, i) => <div className="rounded-lg border p-4 dark:border-slate-800" key={i}><div className="flex justify-between"><strong>{issue.title}</strong><span className="text-xs text-rose-600">{issue.level}</span></div><p className="mt-1 text-sm text-slate-500">{issue.detail}</p>{issue.href && <Link className="mt-2 inline-block text-sm text-emerald-600" href={issue.href}>Inspect record →</Link>}</div>)}</div></section></>;
}
