"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, ArrowRight, Wallet, Info, CircleCheck, HandCoins } from "lucide-react";
import { money } from "@/lib/format";
import { DashboardChart } from "@/components/dashboard-chart";
export type CurrencyPosition = { id: string; code: string; decimals: number; balance: number; available: number; receivable: number; payable: number; accounts: { id: string; name: string; available: number }[] };
export function DashboardOverview({ position, activity, monthLabel }: { position: CurrencyPosition[]; activity: { label: string; income: number; expense: number }[]; monthLabel: string }) {
  const [selected, setSelected] = useState("all"); const shown = position.filter(c => selected === "all" || c.code === selected);
  return <>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-xs text-muted"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Current balances <span className="hidden sm:inline">· All accounts</span></p><div className="segmented" aria-label="Display currency">{position.map(c => <button key={c.id} onClick={() => setSelected(c.code)} aria-pressed={selected === c.code}>{c.code}</button>)}<button onClick={() => setSelected("all")} aria-pressed={selected === "all"}>{position.length === 2 ? "Both" : "All"}</button></div></div>
    <div className={`currency-cards ${shown.length === 1 ? "!grid-cols-1 !grid-flow-row" : ""}`}>{shown.map((c, index) => <section className={`card currency-card ${index === 0 ? "currency-card-primary" : ""}`} key={c.id}>
      <div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><span className="icon-tile !bg-emerald-100 text-emerald-800 dark:!bg-emerald-950 dark:text-emerald-200"><Wallet size={19}/></span><div><h2 className="!text-sm">{c.code === "OMR" ? "Omani Rial" : c.code === "INR" ? "Indian Rupee" : c.code}</h2><p className="mt-0.5 text-xs text-muted">{c.accounts.length} {c.accounts.length === 1 ? "account" : "accounts"} connected</p></div></div><span className="rounded-full border border-slate-200 px-2.5 py-1 text-[10px] font-semibold tracking-wider dark:border-slate-700">{c.code}</span></div>
      <div className="flex items-center gap-2 text-xs font-medium text-muted">Balance · Money you own <Explanation text="Available money + money owed to you − money you owe."/></div>
      <p className="mt-2 flex flex-wrap items-baseline gap-2 font-semibold tracking-[-.04em]"><span className="text-lg font-medium tracking-normal text-muted">{c.code === "INR" ? "₹" : c.code}</span><span className="text-[clamp(1.7rem,3vw,2.5rem)]">{new Intl.NumberFormat(c.code === "INR" ? "en-IN" : "en-GB", { minimumFractionDigits: c.decimals, maximumFractionDigits: c.decimals }).format(c.balance)}</span></p>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200/80 pt-4 dark:border-slate-700"><span className="flex items-center gap-1.5 text-xs text-muted">Actual balance <Explanation text="Money currently available across your wallets and bank accounts, including money borrowed and excluding money lent."/></span><span className="text-lg font-semibold tracking-tight">{money(c.available, c.code, c.decimals)}</span></div>
    </section>)}</div>
    {!position.length && <div className="card text-center"><Wallet className="mx-auto mb-3 text-emerald-700"/><h2>Your overview starts here</h2><p className="mt-2 text-muted">Add a currency and an account to see your balances.</p><Link className="btn-primary mt-4" href="/settings">Open Settings</Link></div>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(280px,1fr)]">
      <section className="card min-w-0"><div className="mb-5 flex items-center justify-between gap-3"><div><h2>Income & expenses</h2><p className="mt-1 text-xs text-muted">{monthLabel} · Each currency shown separately</p></div><span className="icon-tile"><ArrowLeftRightIcon/></span></div>
        <div className={`currency-charts ${shown.length === 1 ? "!grid-cols-1 !grid-flow-row" : ""}`}>{shown.map(c => { const row = activity.find(a => a.label === c.code) ?? { income: 0, expense: 0 }; return <div key={c.id} className="min-w-0"><p className="mb-2 text-xs font-semibold tracking-wider text-muted">{c.code}</p><DashboardChart income={row.income} expense={row.expense} code={c.code}/><div className="mt-4 grid grid-cols-2 gap-2"><div><p className="flex items-center gap-1 text-[11px] text-muted"><ArrowDownLeft size={13} className="text-emerald-700"/>Income</p><p className="mt-1 break-words text-sm font-semibold">+{money(row.income, c.code, c.decimals)}</p></div><div><p className="flex items-center gap-1 text-[11px] text-muted"><ArrowUpRight size={13} className="text-rose-600"/>Expense</p><p className="mt-1 break-words text-sm font-semibold">−{money(row.expense, c.code, c.decimals)}</p></div></div></div>; })}</div>
      </section>
      <section className="card"><div className="flex items-center justify-between"><div><h2>Debt position</h2><p className="mt-1 text-xs text-muted">A clear view of what’s outstanding</p></div><HandCoins size={20} className="text-muted"/></div><div className="mt-6 space-y-6">{shown.map(c => { const total = Math.max(0,c.receivable) + Math.max(0,c.payable); return <div key={c.id}><p className="mb-3 text-xs font-semibold tracking-wider text-muted">{c.code}</p><div className="flex flex-wrap justify-between gap-3 text-sm"><div><p className="mb-1 flex items-center gap-1.5 text-xs text-muted"><ArrowDownLeft size={14} className="text-blue-600"/>Receivable</p><strong>{money(c.receivable,c.code,c.decimals)}</strong></div><div className="text-right"><p className="mb-1 flex items-center justify-end gap-1.5 text-xs text-muted"><ArrowUpRight size={14} className="text-amber-600"/>Payable</p><strong>{money(c.payable,c.code,c.decimals)}</strong></div></div><div className="mt-3 flex h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800" aria-hidden="true">{total > 0 && <><span className="bg-blue-500" style={{ width: `${Math.max(0,c.receivable)/total*100}%` }}/><span className="bg-amber-500" style={{ width: `${Math.max(0,c.payable)/total*100}%` }}/></>}</div>{total === 0 && <p className="mt-2 flex items-center gap-1 text-[11px] text-muted"><CircleCheck size={12}/>No outstanding debt</p>}</div>; })}</div><Link href="/debt" className="mt-6 flex min-h-11 items-center justify-between border-t border-slate-200 pt-4 text-sm font-semibold text-emerald-700 dark:border-slate-800">Open Debt & Credit<ArrowRight size={17}/></Link></section>
    </div>
  </>;
}
function Explanation({ text }: { text: string }) { return <span className="group relative inline-flex"><button type="button" aria-label={text} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full"><Info size={13}/></button><span role="tooltip" className="pointer-events-none absolute bottom-full right-0 z-10 mb-1 hidden w-48 rounded-xl bg-slate-950 p-3 text-xs font-normal leading-relaxed text-white shadow-lg group-hover:block group-focus-within:block">{text}</span></span>; }
function ArrowLeftRightIcon() { return <span className="flex"><ArrowDownLeft size={17}/><ArrowUpRight size={17}/></span>; }
