"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Props = { people: { id: string; name: string }[]; categories: { id: string; name: string }[]; currencies: { id: string; code: string }[]; accounts: { id: string; accountName: string; currencyId: string }[] };
export function DebtForm({ people, categories, currencies, accounts }: Props) {
  const router = useRouter(); const [currencyId, setCurrency] = useState(currencies[0]?.id ?? ""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent<HTMLFormElement>, confirmOverpayment = false) { e.preventDefault(); setBusy(true); const f = new FormData(e.currentTarget); const payload = Object.fromEntries(f); Object.assign(payload, { amount: Number(f.get("amount")), currencyId, confirmOverpayment }); const res = await fetch("/api/debt", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const out = await res.json(); setBusy(false); if (!res.ok) { if (out.error === "OVERPAYMENT_CONFIRMATION_REQUIRED" && window.confirm("This is more than the outstanding amount. Record the excess anyway?")) return submit(e, true); return setError(out.error); } router.push("/debt"); router.refresh(); }
  return <form onSubmit={(e) => submit(e)} className="card grid gap-4 sm:grid-cols-2"><div><label>Person</label><select name="personId" required><option value="">Select person</option>{people.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></div><div><label>Action</label><select name="action" required><option value="MONEY_GIVEN">Money Given</option><option value="MONEY_RECEIVED_BACK">Money Received Back</option><option value="MONEY_BORROWED">Money Borrowed</option><option value="MONEY_PAID_BACK">Money Paid Back</option></select></div><div><label>Category</label><select name="categoryId" required>{categories.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div><label>Currency</label><select value={currencyId} onChange={(e) => setCurrency(e.target.value)}>{currencies.map((c) => <option value={c.id} key={c.id}>{c.code}</option>)}</select></div><div><label>Account</label><select name="accountId" required><option value="">Select account</option>{accounts.filter((a) => a.currencyId === currencyId).map((a) => <option value={a.id} key={a.id}>{a.accountName}</option>)}</select></div><div><label>Amount</label><input name="amount" type="number" min="0.0001" step="0.0001" required/></div><div><label>Date</label><input name="transactionDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required/></div><div><label>Due date</label><input name="dueDate" type="date"/></div><div className="sm:col-span-2"><label>Description</label><input name="description" required/></div><div className="sm:col-span-2"><label>Notes</label><textarea name="notes" rows={2}/></div>{error && <p className="text-sm text-rose-600 sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><button disabled={busy} className="btn-primary">{busy ? "Saving…" : "Save debt entry"}</button></div></form>;
}
