"use client";
import Link from 'next/link';
import {useState,useRef,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import {money} from '@/lib/format';
export type EntryRow={id:string;reference:string;description:string;category:string;type:string;status:string;date:string;updatedAt:string;amount:number;code:string};
export function EntryTable({entries}:{entries:EntryRow[]}){
 const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [deleted,setDeleted]=useState<string[]>([]);const router=useRouter();const all=useRef<HTMLInputElement>(null);
 const active=entries.filter(e=>e.status==='ACTIVE'&&!deleted.includes(e.id));
 useEffect(()=>{if(all.current)all.current.indeterminate=selected.length>0&&selected.length<active.length},[selected.length,active.length]);
 async function remove(){
  if(busy||!selected.length||!window.confirm(`Delete ${selected.length} selected ${selected.length===1?'entry':'entries'}? Their effects on balances will be removed. Records and audit history will be kept.`))return;
  setBusy(true);setError('');setMessage('');const items=active.filter(e=>selected.includes(e.id)).map(e=>({id:e.id,updatedAt:e.updatedAt}));
  try{const res=await fetch('/api/entries/bulk',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});const result=await res.json();if(!res.ok){setError(result.error??'Could not delete the selected entries.');return}setDeleted(d=>[...d,...items.map(i=>i.id)]);setSelected([]);setMessage(`${result.deleted} entries deleted. Balances updated.`);router.refresh()}
  catch{setError('Could not confirm the result. Refresh the journal before trying again.')}finally{setBusy(false)}
 }
 return <><div className="card mb-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm">{selected.length} selected</p><div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" disabled={busy||!selected.length} onClick={()=>setSelected([])}>Clear selection</button><button type="button" className="btn-expense" disabled={busy||!selected.length} onClick={remove}>{busy?'Deleting…':'Delete selected'}</button></div></div><p className="text-sm text-muted">Select individual entries or all active entries shown below (up to 200). Use “Excel imports only” above to review uploaded entries. Deletion keeps an audit record.</p><p className="text-xs text-muted">To import corrected transactions after deleting them, use a fresh Excel template. Previously imported row IDs stay skipped.</p>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-700">{message}</p>}</div>
 <div className="table-wrap"><table><thead><tr><th><input ref={all} type="checkbox" aria-label="Select all active entries shown" disabled={busy||!active.length} checked={active.length>0&&selected.length===active.length} onChange={e=>setSelected(e.target.checked?active.map(r=>r.id):[])}/></th><th>Date</th><th>Reference</th><th>Description</th><th>Type</th><th className="text-right">Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{entries.map(t=>{const isActive=t.status==='ACTIVE'&&!deleted.includes(t.id);return <tr key={t.id}><td>{isActive&&<input type="checkbox" aria-label={`Select ${t.reference}`} disabled={busy} checked={selected.includes(t.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(id=>id!==t.id))}/>}</td><td className="whitespace-nowrap">{t.date.split('-').reverse().join('/')}</td><td><Link className="font-medium text-emerald-600" href={`/entries/${t.id}`}>{t.reference}</Link></td><td>{t.description}<div className="text-xs text-muted">{t.category}</div></td><td>{t.type}</td><td className={`whitespace-nowrap text-right font-semibold ${t.type==='INCOME'?'text-emerald-600':t.type==='EXPENSE'?'text-rose-600':''}`}>{t.type==='INCOME'?'+':t.type==='EXPENSE'?'−':''}{money(t.amount,t.code)}</td><td><span className={`rounded-full px-2 py-1 text-xs ${isActive?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{isActive?'Active':'Deleted'}</span></td><td>{isActive&&<Link className="text-emerald-600" href={`/entries/${t.id}/edit`}>Edit</Link>}</td></tr>})}{!entries.length&&<tr><td colSpan={8} className="py-12 text-center text-muted">No matching entries.</td></tr>}</tbody></table></div></>;
}
