"use client";
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
type Preview={token:string;count:number;skipped:number;rows:{row:number;type:string;date:string;description:string;account:string;category:string;amount:number;notes:string;details:string[];skipped:boolean}[]};
export function ImportExcel(){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [errors,setErrors]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [done,setDone]=useState('');const router=useRouter();
 async function upload(mode:'preview'|'commit'){
  if(!file||busy)return;setBusy(true);setErrors([]);setDone('');
  try{const form=new FormData();form.set('file',file);form.set('mode',mode);if(preview)form.set('token',preview.token);const res=await fetch('/api/import',{method:'POST',body:form});const data=await res.json();if(!res.ok){setErrors(data.errors??[data.error??'Import failed.']);setPreview(null);return}if(mode==='preview')setPreview(data);else{setPreview(null);setDone(`Imported ${data.imported} entries. Skipped ${data.skipped} previously imported entries.`);router.refresh()}}
  catch{setErrors(['Could not reach the server. Preview the same file again to check which rows were saved before retrying.']);setPreview(null)}finally{setBusy(false)}
 }
 return <div className="space-y-6"><section className="card space-y-4"><h2>1. Download and fill the template</h2><p className="text-sm text-muted">Includes your active accounts, categories and subcategories as dropdowns. Supports income, expenses, transfers and exchanges, with up to 200 entries per file. Debt entries use Debt & Credit.</p><a className="btn-primary" href="/api/import/template">Download Excel template</a><p className="text-sm text-muted">Keep each Import ID unchanged when retrying an upload. Already imported IDs are skipped, even if their entries were edited or voided. Do not include transactions already entered manually or in a different template.</p></section>
 <section className="card space-y-4"><h2>2. Upload and preview</h2><label htmlFor="import-file">Completed Excel file (.xlsx, up to 2 MB)</label><input id="import-file" type="file" accept=".xlsx" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setErrors([]);setDone('')}}/><button type="button" className="btn-secondary" disabled={!file||busy} onClick={()=>upload('preview')}>{busy?'Processing…':'Preview import'}</button>{errors.length>0&&<div role="alert" className="max-h-80 overflow-y-auto rounded-xl bg-rose-50 p-4 text-sm text-rose-800 dark:bg-rose-950 dark:text-rose-200"><p className="mb-2 font-semibold">Please review these issues</p><ul className="list-disc space-y-2 pl-5">{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}{done&&<p role="status" className="text-emerald-700">{done} <Link className="underline" href="/entries">View entries</Link></p>}</section>
 {preview&&<section className="card space-y-4"><h2>3. Review and confirm</h2><p>{preview.count} new entries · {preview.skipped} already imported</p><p className="text-sm text-muted">These entries will change your balances. Check dates, currencies, amounts and account choices below. Nothing is saved until you confirm.</p><div className="table-wrap"><table><thead><tr><th>Excel row</th><th>Date / Type</th><th>Description</th><th>Account</th><th>Category</th><th>Amount</th><th>Status / Details</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.row}><td>{r.row}</td><td className="whitespace-nowrap">{r.date}<br/>{r.type}</td><td>{r.description}</td><td>{r.account}</td><td>{r.category||'Not applicable'}</td><td>{r.amount}</td><td>{r.skipped?'Skip — previously imported':'New entry'}<details><summary className="mt-2 text-emerald-700">All fields</summary><ul className="mt-2 space-y-1 text-xs">{r.details.map((d,i)=><li key={i}>{d}</li>)}{r.notes&&<li>Notes: {r.notes}</li>}</ul></details></td></tr>)}</tbody></table></div><button type="button" className="btn-primary" disabled={busy||!preview.count} onClick={()=>upload('commit')}>{busy?'Importing…':`Confirm import of ${preview.count} ${preview.count===1?'entry':'entries'}`}</button></section>}
 </div>;
}
