import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { money } from "@/lib/format";

export default async function EntriesPage({ searchParams }: { searchParams: Promise<{ type?: string; q?: string; status?: string }> }) {
  const { type, q, status } = await searchParams;
  const entries = await db.transaction.findMany({ where: { status: status === "all" ? undefined : status === "deleted" ? "VOIDED" : "ACTIVE", type: type && ["INCOME","EXPENSE","TRANSFER","EXCHANGE"].includes(type) ? type as never : undefined, OR: q ? [{ description: { contains: q } }, { notes: { contains: q } }, { reference: { contains: q } }] : undefined }, include: { category: { include: { parent: true } }, allocations: { include: { account: { include: { currency: true } } } }, transfer: { include: { sourceAccount: { include: { currency: true } }, destinationAccount: true } }, exchange: { include: { sourceAccount: { include: { currency: true } }, destinationAccount: { include: { currency: true } } } } }, orderBy: [{ transactionDate: "desc" }, { createdAt: "desc" }], take: 200 });
  return <><PageHeader title="Entries" description="Unified journal of all financial activity" actions={<Link href="/entries/new" className="btn-primary">+ New entry</Link>}/><form className="card mb-5 grid gap-3 sm:grid-cols-[1fr_160px_160px_auto]"><input name="q" placeholder="Search description, notes, reference…" defaultValue={q}/><select name="type" defaultValue={type}><option value="">All types</option><option>INCOME</option><option>EXPENSE</option><option>TRANSFER</option><option>EXCHANGE</option></select><select name="status" defaultValue={status ?? "active"}><option value="active">Active entries</option><option value="deleted">Deleted entries</option><option value="all">All entries</option></select><button className="btn-secondary">Filter</button></form><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Description</th><th>Type</th><th className="text-right">Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{entries.map((t) => { const code = t.allocations[0]?.account.currency.code ?? t.transfer?.sourceAccount.currency.code ?? t.exchange?.sourceAccount.currency.code ?? "OMR"; return <tr key={t.id}><td>{t.transactionDate.toLocaleDateString("en-GB")}</td><td><Link className="font-medium text-emerald-600" href={`/entries/${t.id}`}>{t.reference}</Link></td><td>{t.description}<div className="text-xs text-slate-400">{[t.category?.parent?.name, t.category?.name].filter(Boolean).join(" / ")}</div></td><td>{t.type}</td><td className={`text-right font-semibold ${t.type === "INCOME" ? "text-emerald-600" : t.type === "EXPENSE" ? "text-rose-600" : ""}`}>{money(Number(t.amount), code)}</td><td><span className={`rounded-full px-2 py-1 text-xs ${t.status === "ACTIVE" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{t.status === "ACTIVE" ? "Active" : "Deleted"}</span></td><td>{t.status === "ACTIVE" && <Link className="text-emerald-600" href={`/entries/${t.id}/edit`}>Edit</Link>}</td></tr>; })}{!entries.length && <tr><td colSpan={7} className="py-12 text-center text-slate-500">No matching entries.</td></tr>}</tbody></table></div></>;
}
