import { EntryFilters } from "@/components/entry-filters";
import { TransactionType } from "@prisma/client";
import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { EntryTable } from "@/components/entry-table";

export default async function EntriesPage({ searchParams }: { searchParams: Promise<{ type?: string; q?: string; status?: string; source?: string }> }) {
  const { type, q, status, source } = await searchParams;
  const entries = await db.transaction.findMany({ where: { reference: source === "excel" ? { startsWith: "IMP-" } : undefined, status: status === "all" || status === "" || status === "active,deleted" || status === "deleted,active" ? undefined : status === "deleted" ? "VOIDED" : "ACTIVE", type: type ? {in:type.split(",").filter(t=>["INCOME","EXPENSE","TRANSFER","EXCHANGE"].includes(t)) as TransactionType[]} : undefined, OR: q ? [{ description: { contains: q } }, { notes: { contains: q } }, { reference: { contains: q } }] : undefined }, include: { category: { include: { parent: true } }, allocations: { include: { account: { include: { currency: true } } } }, transfer: { include: { sourceAccount: { include: { currency: true } }, destinationAccount: true } }, exchange: { include: { sourceAccount: { include: { currency: true } }, destinationAccount: { include: { currency: true } } } } }, orderBy: [{ transactionDate: "desc" }, { createdAt: "desc" }], take: 200 });
  return <><PageHeader title="Entries" description="Unified journal of all financial activity" actions={<><a href="/api/import/template" className="btn-secondary">Download Excel</a><Link href="/entries/import" className="btn-secondary">Import Excel</Link><Link href="/entries/new" className="btn-primary">+ New entry</Link></>}/><EntryFilters key={`${type}-${status}-${q}-${source}`} type={type} q={q} status={status} source={source}/><EntryTable key={JSON.stringify([type,q,status,source,entries.map(t=>[t.id,t.updatedAt])])} entries={entries.map(t=>({id:t.id,reference:t.reference,description:t.description,type:t.type,status:t.status,date:t.transactionDate.toISOString().slice(0,10),updatedAt:t.updatedAt.toISOString(),amount:Number(t.amount),category:[t.category?.parent?.name,t.category?.name].filter(Boolean).join(" / "),code:t.allocations[0]?.account.currency.code??t.transfer?.sourceAccount.currency.code??t.exchange?.sourceAccount.currency.code??"OMR"}))}/></>;
}
