// Fictional fixtures used only by this local visual preview. No production database is accessed.
export const currencies=[{id:'omr',code:'OMR',name:'Omani Rial',symbol:'ر.ع.',decimalPlaces:3,status:'ACTIVE'},{id:'inr',code:'INR',name:'Indian Rupee',symbol:'₹',decimalPlaces:2,status:'ACTIVE'}];
export const accounts=[{id:'cash',accountName:'OMR Cash',currencyId:'omr',currency:currencies[0],type:'CASH',status:'ACTIVE'},{id:'bank',accountName:'Bank Muscat',currencyId:'omr',currency:currencies[0],type:'BANK',status:'ACTIVE'},{id:'india',accountName:'INR Cash',currencyId:'inr',currency:currencies[1],type:'CASH',status:'ACTIVE'}];
export const categories=[{id:'food',name:'Food & Dining',type:'EXPENSE',parentId:null,status:'ACTIVE',sortOrder:0},{id:'dining',name:'Restaurants',type:'EXPENSE',parentId:'food',parent:{id:'food',name:'Food & Dining'},status:'ACTIVE',sortOrder:1},{id:'transport',name:'Transport',type:'EXPENSE',parentId:null,status:'ACTIVE',sortOrder:2},{id:'salary',name:'Salary',type:'INCOME',parentId:null,status:'ACTIVE',sortOrder:0}];
const rows=[['t1','EXPENSE','Lunch with friends',12.5,'omr',categories[0]],['t2','INCOME','Monthly salary',850,'omr',categories[3]],['t3','EXPENSE','Weekend groceries',1530,'inr',categories[0]],['t4','INCOME','Freelance project',5000,'inr',categories[3]]].map(([id,type,description,amount,currencyId,category],i)=>({id,type,description,amount,currencyId,category,categoryId:category.id,reference:`${type==='EXPENSE'?'EXP':'INC'}-20261002-00${i}`,transactionDate:new Date('2026-10-02'),createdAt:new Date('2026-10-02'),updatedAt:new Date('2026-10-02'),status:'ACTIVE',notes:null,transfer:null,exchange:null,attachments:[],allocations:[{id:'a'+i,account:accounts.find(a=>a.currencyId===currencyId),accountId:accounts.find(a=>a.currencyId===currencyId).id,amount}]}));
export const position=[{id:'omr',code:'OMR',decimals:3,balance:201.545,available:201.545,receivable:0,payable:0,accounts:[{id:'cash',name:'OMR Cash',type:'CASH',available:61.545},{id:'bank',name:'Bank Muscat',type:'BANK',available:140}]},{id:'inr',code:'INR',decimals:2,balance:4047,available:3847,receivable:200,payable:0,accounts:[{id:'india',name:'INR Cash',type:'CASH',available:3847}]}];
export async function getFinancialPosition(){return position}
const model=data=>({findMany:async()=>data,count:async()=>data.length,findUnique:async()=>data[0],findUniqueOrThrow:async()=>data[0]});
export const db={currency:model(currencies),account:model(accounts),category:model(categories),transaction:model(rows),transactionAllocation:model([]),debtCategory:model([{id:'loan',name:'Personal Loan',status:'ACTIVE'}]),debtTransaction:model([]),person:model([{id:'p1',name:'Alex',status:'ACTIVE'}]),exchangeRate:model([]),budget:model([{id:'b1',category:categories[0],currencyMode:'OMR',amount:100,isDefault:true,effectiveMonth:null}]),transfer:model([]),exchange:model([]),auditLog:model([])};
