import { addPerson } from "@/app/actions";
import { DebtForm } from "@/components/debt-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { money, serialize } from "@/lib/format";

export default async function DebtPage() {
  const [people, categories, currencies, accounts, rows] = await Promise.all([db.person.findMany({ where: { status: "ACTIVE" }, orderBy: { name: "asc" } }), db.debtCategory.findMany({ where: { status: "ACTIVE" }, orderBy: { sortOrder: "asc" } }), db.currency.findMany({ where: { status: "ACTIVE" } }), db.account.findMany({ where: { status: "ACTIVE" } }), db.debtTransaction.findMany({ where: { status: "ACTIVE" }, include: { person: true, currency: true }, orderBy: { transactionDate: "desc" } })]);
  const summaries = people.flatMap((p) => currencies.map((c) => { const own = rows.filter((r) => r.personId === p.id && r.currencyId === c.id); const receivable = own.filter((x) => x.action === "MONEY_GIVEN").reduce((s,x) => s + Number(x.amount), 0) - own.filter((x) => x.action === "MONEY_RECEIVED_BACK").reduce((s,x) => s + Number(x.amount), 0); const payable = own.filter((x) => x.action === "MONEY_BORROWED").reduce((s,x) => s + Number(x.amount), 0) - own.filter((x) => x.action === "MONEY_PAID_BACK").reduce((s,x) => s + Number(x.amount), 0); return { person: p, currency: c, receivable, payable }; }).filter((x) => x.receivable || x.payable));
  return <><PageHeader title="Debt & Credit" description="Receivables and payables stay separate from normal entries"/><div className="grid gap-6 xl:grid-cols-[1fr_1.4fr]"><DebtForm people={serialize(people)} categories={serialize(categories)} currencies={serialize(currencies)} accounts={serialize(accounts)}/><section className="card"><h2 className="mb-4 font-semibold">Current position by person</h2><div className="divide-y dark:divide-slate-800">{summaries.map((s) => <div key={`${s.person.id}-${s.currency.id}`} className="py-3"><div className="flex justify-between"><strong>{s.person.name}</strong><span>{s.currency.code}</span></div><div className="mt-1 flex gap-4 text-sm"><span className="text-emerald-600">Receivable {money(s.receivable, s.currency.code, s.currency.decimalPlaces)}</span><span className="text-rose-600">Payable {money(s.payable, s.currency.code, s.currency.decimalPlaces)}</span></div></div>)}{!summaries.length && <p className="py-8 text-center text-sm text-slate-500">No outstanding balances.</p>}</div><form action={addPerson} className="mt-6 grid grid-cols-[1fr_1fr_auto] gap-2 border-t pt-5 dark:border-slate-800"><input name="name" placeholder="New person" required/><input name="contact" placeholder="Contact (optional)"/><button className="btn-secondary">Add</button></form></section></div><section className="card mt-6"><h2 className="mb-4 font-semibold">Recent debt activity</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Person</th><th>Action</th><th>Description</th><th className="text-right">Amount</th></tr></thead><tbody>{rows.slice(0,100).map((r) => <tr key={r.id}><td>{r.transactionDate.toLocaleDateString("en-GB")}</td><td>{r.person.name}</td><td>{r.action.replaceAll("_", " ")}</td><td>{r.description}</td><td className="text-right font-medium">{money(Number(r.amount), r.currency.code, r.currency.decimalPlaces)}</td></tr>)}</tbody></table></div></section></>;
}
